# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parser": "spam.ipynb",
         "args": "spam.ipynb",
         "input_params": "spam.ipynb",
         "df": "spam.ipynb",
         "y": "spam.ipynb",
         "X": "spam.ipynb"}

modules = ["train.py"]

doc_url = "https://nbdev.fast.ai/"

git_url = "https://github.com/fastai/nbdev/tree/master/"

def custom_doc_links(name): return None
